version: '3.6'

services:

  router-lambda:
    image: lambci/lambda:build-python3.6
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./dist:/var/task/dist
      - ./docker/bin:/var/task/bin
      - ./src/eablib/eab:/var/task/common/eab
      - ./src/picolib/pico:/var/task/common/pico
      - ./src/router:/var/task/adapter
    command: sh /var/task/bin/package.sh router
